# Generated by Django 4.1.4 on 2022-12-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], max_length=10)),
                ('status', models.CharField(choices=[('0', 'INACTIVE'), ('1', 'ACTIVE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='package_type_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='state_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=25)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country')),
            ],
        ),
        migrations.CreateModel(
            name='package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('package_image', models.ImageField(upload_to='photos')),
                ('package_video', models.FileField(upload_to='videos')),
                ('no_of_day', models.IntegerField()),
                ('package_description', models.TextField()),
                ('package_price', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.login_table')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.package_type_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.TextField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.login_table')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.package_type_table')),
            ],
        ),
        migrations.CreateModel(
            name='detail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.city_table')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.login_table')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.state_table')),
            ],
        ),
        migrations.AddField(
            model_name='city_table',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.state_table'),
        ),
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('0', 'pending'), ('1', 'CONFIRRMED'), ('2', 'canceled')], max_length=10)),
                ('payment_status', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.login_table')),
            ],
        ),
    ]
