# Generated by Django 4.1.4 on 2022-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_table',
            name='display_pic',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
