# Generated by Django 4.1.4 on 2023-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_package_details_package_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful')], max_length=10),
        ),
    ]
