# Generated by Django 4.1.6 on 2023-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_booking_details_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('AGENT', 'agent'), ('USER', 'user')], max_length=10),
        ),
    ]
