# Generated by Django 4.1.6 on 2023-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_login_table_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('user', 'user')], max_length=10),
        ),
    ]
