# Generated by Django 4.1.6 on 2023-02-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_login_table_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details',
            name='package_video',
        ),
    ]
