# Generated by Django 4.1.6 on 2023-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_remove_package_details_package_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='package_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=50),
        ),
    ]
