# Generated by Django 4.1.6 on 2023-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_package_details_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details',
            name='package_status',
            field=models.CharField(choices=[(True, 'open'), (False, 'closed')], default=True, max_length=50),
        ),
    ]
