# Generated by Django 4.1.6 on 2023-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_package_details_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='status_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_details',
            name='package_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=50),
        ),
    ]
