# Generated by Django 4.1.6 on 2023-02-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_package_details_status_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.package_details'),
        ),
    ]
