# Generated by Django 4.1.6 on 2023-02-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_booking_details_package_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_details',
            old_name='package_id',
            new_name='package_data',
        ),
    ]
