# Generated by Django 4.1.6 on 2023-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_rename_package_id_booking_details_package_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful')], default='pending', max_length=10),
        ),
    ]
