# Generated by Django 4.1.6 on 2023-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_booking_details_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
