# Generated by Django 4.1.6 on 2023-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_booking_details_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='package_id',
        ),
    ]
