# Generated by Django 4.1.6 on 2023-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_remove_feedback_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(default='', max_length=300),
        ),
    ]
