# Generated by Django 4.1.6 on 2023-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_feedback_comment_alter_feedback_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('comment', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
