# Generated by Django 4.1.6 on 2023-02-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactform',
        ),
    ]
