# Generated by Django 4.1.7 on 2023-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_rename_contact_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('card_cvv', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('card_balance', models.IntegerField(default=1000000)),
            ],
        ),
    ]
