# Generated by Django 4.1.7 on 2023-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_card_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='booking_name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='no_of_adults',
            field=models.CharField(default='5', max_length=50),
        ),
    ]
