# Generated by Django 4.1.7 on 2023-03-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_booking_details_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='no_of_child',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
