# Generated by Django 4.1.7 on 2023-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_booking_details_no_of_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package_details',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
