# Generated by Django 4.1.7 on 2023-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_package_details_adults_package_details_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='children',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='From',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
