# Generated by Django 4.1.7 on 2023-04-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_remove_package_details_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='Package_date',
            field=models.DateField(null=True),
        ),
    ]
